
version: '3.6'

services:
  template-service:
    image: 'us-docker.pkg.dev/omg-img/ordermygear/go:v1.17.13-1'
    working_dir: '/workspace'
    volumes:
      - '${DEV_DIR_template_service:?DEV_DIR_template_service}:/workspace:cached'
    command: 'tail -f /dev/null'
    ports:
      - '40000'
    security_opt:
      - 'seccomp:unconfined'
