{{ if eq .Values.global.deploySecrets "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: template-service
  namespace: "{{ .Values.global.namespace }}"
  labels:
    app: template-service
type: Opaque
data:
  dsn: "{{ base64encode .Values.templateService.dsn }}"
  service_credentials.json: "{{ base64encode .Values.templateService.gcpCredentials }}"
  {{ end -}}
