apiVersion: v1
kind: Service
metadata:
  name: template-service
  namespace: "{{ .Values.global.namespace }}"
  labels:
    app: template-service
spec:
  selector:
    app: template-service
  ports:
    - name: http
      targetPort: http
      port: 80
